import { beforeEach, describe, test } from "vitest";
import { expect } from "chai";
import { Board } from "../src/Board.mjs";
import { Tetromino } from "../src/Tetromino.mjs";

describe("Falling T shape tetrominoes", () => {
  let board;
  beforeEach(() => {
    board = new Board(10, 6);
    board.drop(Tetromino.T_SHAPE);
  });

  describe("can be rotated left", () => {
    test("once", () => {
      board.rotateLeft();
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TT.....
         ....T.....
         ..........
         ..........
         ..........`
      );
    });

    test("twice", () => {
      board.rotateLeft();
      board.rotateLeft();
      expect(board.toString()).to.equalShape(
        `...TTT....
         ....T.....
         ..........
         ..........
         ..........
         ..........`
      );
    });

    test("3 times", () => {
      board.rotateLeft();
      board.rotateLeft();
      board.rotateLeft();
      expect(board.toString()).to.equalShape(
        `....T.....
         ....TT....
         ....T.....
         ..........
         ..........
         ..........`
      );
    });

    test("4 times", () => {
      board.rotateLeft();
      board.rotateLeft();
      board.rotateLeft();
      board.rotateLeft();
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TTT....
         ..........
         ..........
         ..........
         ..........`
      );
    });
  });

  describe("cannot be rotated left", () => {
    test("if there is no space", () => {
      board.board[2][4] = "X";
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TTT....
         ....X.....
         ..........
         ..........
         ..........`
      );
      board.rotateLeft();
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TTT....
         ....X.....
         ..........
         ..........
         ..........`
      );
    });
  });

  describe("can be rotated right", () => {
    test("once", () => {
      board.rotateRight();
      expect(board.toString()).to.equalShape(
        `....T.....
         ....TT....
         ....T.....
         ..........
         ..........
         ..........`
      );
    });

    test("twice", () => {
      board.rotateRight();
      board.rotateRight();
      expect(board.toString()).to.equalShape(
        `...TTT....
         ....T.....
         ..........
         ..........
         ..........
         ..........`
      );
    });

    test("3 times", () => {
      board.rotateRight();
      board.rotateRight();
      board.rotateRight();
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TT.....
         ....T.....
         ..........
         ..........
         ..........`
      );
    });

    test("4 times", () => {
      board.rotateRight();
      board.rotateRight();
      board.rotateRight();
      board.rotateRight();
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TTT....
         ..........
         ..........
         ..........
         ..........`
      );
    });
  });

  describe("cannot be rotated right", () => {
    test("if there is no space", () => {
      board.board[2][4] = "X";
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TTT....
         ....X.....
         ..........
         ..........
         ..........`
      );
      board.rotateRight();
      expect(board.toString()).to.equalShape(
        `....T.....
         ...TTT....
         ....X.....
         ..........
         ..........
         ..........`
      );
    });
  });
});

describe("Falling O shape tetrominoes", () => {
  const boardWithOShape = `....OO....\n....OO....\n..........\n..........\n..........\n..........`;

  let board;
  beforeEach(() => {
    board = new Board(10, 6);
    board.drop(Tetromino.O_SHAPE);
  });

  describe("cannot be rotated left", () => {
    for (let i = 0; i < 4; i++) {
      test(`${i} times`, () => {
        board.rotateLeft();
        expect(board.toString()).to.equalShape(boardWithOShape);
      });
    }
  });

  describe("cannot be rotated right", () => {
    for (let i = 0; i < 4; i++) {
      test(`${i} times`, () => {
        board.rotateRight();
        expect(board.toString()).to.equalShape(boardWithOShape);
      });
    }
  });
});
